spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:62943/poc_docker_container?loggerLevel=OFF}
    username: ${DATABASE_USER:admin}
    password:  ${DATABASE_PASSWORD:admin}
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
      group: "unique-group-123"
      topic: "consumer-topic"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    com.example.testcontainers : "DEBUG"